### ISSUE TITLE
Startup issue.

### ISSUE THREAD

**Issue by k0nsl** [Peer5/ShareFest#88]
`npm start` yields:
```
root@ragnarok:~/ShareFest# npm start

> Sharefest@1.0.0 start /root/ShareFest
> node sharefest/server.js

/root/ShareFest/node_modules/express/lib/express.js:99
      throw new Error('Most middleware (like ' + name + ') is no longer bundled with Express and must be installed separately. Please see https://github.com/senchalabs/connect#middleware.');
      ^

Error: Most middleware (like json) is no longer bundled with Express and must be installed separately. Please see https://github.com/senchalabs/connect#middleware.
    at Function.get (/root/ShareFest/node_modules/express/lib/express.js:99:13)
    at Object.<anonymous> (/root/ShareFest/sharefest/server.js:27:16)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.runMain (module.js:590:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)

npm ERR! Linux 3.16.0-4-amd64
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! node v6.6.0
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE
npm ERR! Sharefest@1.0.0 start: `node sharefest/server.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the Sharefest@1.0.0 start script 'node sharefest/server.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the Sharefest package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node sharefest/server.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs Sharefest
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls Sharefest
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/ShareFest/npm-debug.log
```
...and yes, I did install the dependencies. Any ideas?

**Comment by derhuerst** [comment]
This is because this project [use a non-semver version range for `express`](https://github.com/Peer5/ShareFest/blob/c69f7f0/package.json#L7). Changing it to `^3.3.0` would get you the latest version of Express API-compatible with `3.3.0`.

In fact, all of the dependencies are either invalid or don't adhere to best practices in the JS ecosystem.

**Comment by k0nsl** [comment]
Ah, I see. Thank you @derhuerst; it works now :)

**Comment by derhuerst** [comment]
Would you mind submitting a PR? ;)
